version: "3.8"
services:
  nodeserver:
    build:
      context: ./app
    ports:
      - "5000:5000"
    links:
      - dbserver
  reactserver:
    build:
      context: ./client
    ports:
      - "3000:3000"
  dbserver:
    image: mongo
    container_name: mongodb
    volumes:
    - data:/data/db
    ports:
      - "27017:27017"
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certificates:/etc/nginx/certs
    depends_on:
      - nodeserver
      - reactserver
volumes:
  data:


