version: "3.8"
services:
  nodeserver:
    build:
      context: ./app
    ports:
      - "5000:5000"
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certificates:/etc/nginx/certs
    depends_on:
      - nodeserver


